### ISSUE TITLE
If build fails on a unit test, must re-setup miniconda

### ISSUE THREAD

**Issue by danielsf** [mjuric/conda-lsst#29]
The build for the Sims Stack has been failing on an astropy-helpers unit test.

Whenever it does, I must re-run

conda build recipes/static/patchelf
conda build recipes/static/eups
conda build recipes/static/legacy_configs

before attempting another build.  If I do not, I get the following error message

updating built package cache [from file:///Users/danielsf/physics/conda-lsst-sfd/conda-lsst/miniconda/conda-bld/osx-64] ....Traceback (most recent call last):
  File "/Users/danielsf/physics/conda-lsst-sfd/conda-lsst/bin/conda-lsst", line 1130, in <module>
    db.reindex(channels)
  File "/Users/danielsf/physics/conda-lsst-sfd/conda-lsst/bin/conda-lsst", line 331, in reindex
    self.reindex_channel(channel)
  File "/Users/danielsf/physics/conda-lsst-sfd/conda-lsst/bin/conda-lsst", line 402, in reindex_channel
    download_url(pkgurl, fp)
  File "/Users/danielsf/physics/conda-lsst-sfd/conda-lsst/bin/conda-lsst", line 150, in download_url
    r.raise_for_status()
  File "/Users/danielsf/physics/conda-lsst-sfd/conda-lsst/miniconda/lib/python2.7/site-packages/requests/models.py", line 837, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: None for url: None

**Comment by mjuric** [comment]
I suspect this is because `conda`'s package cache gets out out of sync with what truly is in the build directory. If this happens again, try running:

```
cd /Users/danielsf/physics/conda-lsst-sfd/conda-lsst/miniconda/conda-bld/osx-64
conda index
```

I could try to defend against it by proactively calling `conda index` for all local directories with packages, but this sounds like a `conda` bug. Is there a way to consistently reproduce it?
