### ISSUE TITLE
legacy_config recipe fails

### ISSUE THREAD

**Issue by jhoblitt** [mjuric/conda-lsst#36]
This may be related to the failure mode seen in #35.

```
# conda build recipes/static/legacy_configs/
Removing old build environment
Removing old work directory
BUILD START: legacy_configs--2
Fetching package metadata: ......
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/conda-lsst/miniconda/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/conda-lsst/miniconda/lib/python2.7/site-packages/conda_build/main_build.py", line 190, in main
    args_func(args, p)
  File "/conda-lsst/miniconda/lib/python2.7/site-packages/conda_build/main_build.py", line 468, in args_func
    args.func(args, p)
  File "/conda-lsst/miniconda/lib/python2.7/site-packages/conda_build/main_build.py", line 391, in execute
    override_channels=args.override_channels, include_recipe=args.include_recipe)
  File "/conda-lsst/miniconda/lib/python2.7/site-packages/conda_build/build.py", line 380, in build
    override_channels=override_channels)
  File "/conda-lsst/miniconda/lib/python2.7/site-packages/conda_build/build.py", line 283, in create_env
    actions = plan.install_actions(prefix, index, specs)
  File "/conda-lsst/miniconda/lib/python2.7/site-packages/conda/plan.py", line 411, in install_actions
    update_deps=update_deps):
  File "/conda-lsst/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 1046, in solve
    for pkg in self.get_pkgs(ms, max_only=max_only):
  File "/conda-lsst/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 544, in get_pkgs
    pkgs = [Package(fn, self.index[fn]) for fn in self.find_matches(ms)]
  File "/conda-lsst/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 360, in __init__
    self.norm_version = VersionOrder(self.version)
  File "/conda-lsst/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 149, in __init__
    raise ValueError("Empty version string.")
ValueError: Empty version string.
```

**Comment by mjuric** [comment]
Correct. #35 polluted the directory with built packages by adding one that has an empty version (probably something like `eups--.tar.bz2`), and then `conda` isn't robust enough to survive such corruption.

Find the offending package (it'll be in `$CONDA_ROOT/conda-bld/$CONDA_ARCH`), delete it, and then run `conda index .` in that directory (to re-index the repository).

Reopen if this doesn't fix it.
