### ISSUE TITLE
Is there a special step needed to tell conda-lsst about published builds?

### ISSUE THREAD

**Issue by danielsf** [mjuric/conda-lsst#54]
I just built a new version of lsst_sims on buildbot (build b1971)

When I run

```
conda lsst make-recipes build:b1971 lsst_sims --build
```

I get an early failure ending in

```
updating built package cache [from http://eupsforge.net/conda/dev/osx-64] ....................................................................... done.
https://raw.githubusercontent.com/lsst/versiondb/master/manifests/b1971.txt
Traceback (most recent call last):
  File "/Users/danielsf/physics/conda-lsst/bin/conda-lsst", line 149, in <module>
    args.func(config, args)
  File "/Users/danielsf/physics/conda-lsst/bin/conda-lsst", line 23, in main_make_recipes
    manifest, tags = build_manifest_for_products(args.products, args.manifest)
  File "/Users/danielsf/physics/conda-lsst/conda_lsst/utils.py", line 67, in build_manifest_for_products
    build_id, manifest_lines = load_manifest(manifestFnOrId)
  File "/Users/danielsf/physics/conda-lsst/conda_lsst/utils.py", line 32, in load_manifest
    with contextlib.closing(urllib2.urlopen(url)) as fp:
  File "/Users/danielsf/physics/conda-lsst/miniconda/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/danielsf/physics/conda-lsst/miniconda/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/Users/danielsf/physics/conda-lsst/miniconda/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Users/danielsf/physics/conda-lsst/miniconda/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/Users/danielsf/physics/conda-lsst/miniconda/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/Users/danielsf/physics/conda-lsst/miniconda/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
```

which makes it look to me like conda-lsst cannot find build b1971.  Is there a special way we need to publish builds to make them visible to conda-lsst?

**Comment by danielsf** [comment]
The problem is that, when I logged onto lsst-dev to create the build, I used

```
ssh -X -A lsstsw@lsst-dev.ncsa.illinois.edu
```

so that, when lsst-build tried to update versiondb, it identified me as danielsf (who doesn't have permission), as opposed to lsstsw (who does).

In order for builds to get correctly published to versiondb, make sure to log on using

```
ssh lsstsw@lsst-dev.ncsa.illinois.edu
```

(no ssh forwarding)
