### ISSUE TITLE
conda lsst make-recipes failure

### ISSUE THREAD

**Issue by rhiannonlynne** [mjuric/conda-lsst#72]
I'm trying to build a conda version of the new sims release. But conda lsst make-recipes is failing. 
This is a new conda-lsst installation, so a new miniconda. Conda is version 4.0.8.

Here is the failure in context: (note this is on lsst-dev)

-bash-4.1$ conda lsst make-recipes build:b2084 lsst_apps lsst_sims
updating built package cache [from file:///ssd/ljones/conda-lsst/miniconda/conda-bld/linux-64]    not found. skipping.
updating built package cache [from http://eupsforge.net/conda/dev/linux-64] ................................................................................... done.
https://raw.githubusercontent.com/lsst/versiondb/master/manifests/b2084.txt
generating recipes: 
  lsst-python-eups-configs-0.0.4...  
Traceback (most recent call last):
  File "/ssd/ljones/conda-lsst/bin/conda-lsst", line 149, in <module>
    args.func(config, args)
  File "/ssd/ljones/conda-lsst/bin/conda-lsst", line 26, in main_make_recipes
    generator.generate(manifest)
  File "/ssd/ljones/conda-lsst/conda_lsst/recipe_maker.py", line 278, in generate
    self.gen_conda_package(product, sha, version, giturl, deps)
  File "/ssd/ljones/conda-lsst/conda_lsst/recipe_maker.py", line 94, in gen_conda_package
    bplus, rplus = self.add_missing_deps(conda_name)    # manually add any missing dependencies
  File "/ssd/ljones/conda-lsst/conda_lsst/recipe_maker.py", line 259, in add_missing_deps
    }.get(kind, lambda dep: None)(dep)
  File "/ssd/ljones/conda-lsst/conda_lsst/recipe_maker.py", line 247, in copy_additional_recipe
    _copy_recipe(name)
  File "/ssd/ljones/conda-lsst/conda_lsst/recipe_maker.py", line 222, in _copy_recipe
    ret = subprocess.check_output('conda search --use-local --spec --json %s=%s' % (name, version), shell=True).strip()
  File "/ssd/ljones/conda-lsst/miniconda/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'conda search --use-local --spec --json eups=2.0.2' returned non-zero exit status 1
-bash-4.1$ 

And if I enter that failing command by hand, I get the following: 
-bash-4.1$ conda search --use-local --spec --json eups=2.0.2
{
  "error": "An unexpected error has occurred, please consider sending the\nfollowing traceback to the conda GitHub issue tracker at:\n\n    https://github.com/conda/conda/issues\n\nInclude the output of the command 'conda info' in your report.\n\nTraceback (most recent call last):\n  File \"/ssd/ljones/conda-lsst/miniconda/lib/python2.7/site-packages/conda/cli/main.py\", line 146, in args_func\n    args.func(args, p)\n  File \"/ssd/ljones/conda-lsst/miniconda/lib/python2.7/site-packages/conda/cli/main_search.py\", line 120, in execute\n    execute_search(args, parser)\n  File \"/ssd/ljones/conda-lsst/miniconda/lib/python2.7/site-packages/conda/cli/main_search.py\", line 215, in execute_search\n    if ms and name != ms.name:\nAttributeError: 'str' object has no attribute 'name'\n", 
  "error_type": "UnexpectedError"
}

Change in behavior in conda? Change in how conda-lsst is expecting to handle this information?

**Comment by rhiannonlynne** [comment]
Happens on el cap too.

**Comment by mjuric** [comment]
Apply (by hand) the patch described here: https://github.com/conda/conda/pull/2343.

This is a conda bug.

**Comment by rhiannonlynne** [comment]
Ugh, sorry - this is clearly a conda bug.

**Comment by rhiannonlynne** [comment]
Thanks for the patch, Mario.

**Comment by mjuric** [comment]
This is expected to be resolved in `conda 4.1.0`, expected to be out on Monday (see https://github.com/conda/conda/pull/2654#issuecomment-225332410)
